import Link from "next/link";
import { Disclosure } from "@/components/ui/disclosure";

export default function LandingPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-5xl flex-col px-6 py-16">
      <header className="max-w-3xl">
        <p className="text-xs font-medium uppercase tracking-wider text-primary">
          CIKM 2026 Demo Track
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight md:text-5xl">
          SAGE
        </h1>
        <p className="mt-4 text-lg text-muted-foreground md:text-xl">
          A guardrailed LLM tutor that scaffolds self-regulated learning for adult
          learners. <span className="font-medium text-foreground">SAGE</span>{" "}
          (Scaffolded, Audited, Guided Education) wraps a commercial Large Language
          Model (LLM) with interface-level scaffolds that prompt learners to plan,
          paraphrase, and attempt before the tutor answers, so it guides thinking
          instead of handing over answers. A counterfactual fairness audit runs as a
          secondary safeguard, checking the tutor responds consistently across
          learner backgrounds.
        </p>
      </header>

      <section className="mt-12 grid gap-4 md:grid-cols-2">
        <Card
          href="/demo"
          title="Try the public demo"
          subtitle="Side-by-side comparison: unrestricted GPT vs the guardrailed tutor"
          accent="primary"
          badge="Recommended"
        />
        <Card
          href="/admin/login"
          title="Tutor sign in"
          subtitle="Configure cohorts, generate invites, view analytics"
        />
        <Card
          href="/chat"
          title="Student chat"
          subtitle="Cohort-aware tutor. Sign in via your tutor's invite URL first"
        />
        <Card
          href="/audit"
          title="Standalone fairness audit"
          subtitle="Run counterfactual probes on a single prompt"
        />
      </section>

      <section className="mt-12 rounded-xl border bg-muted/30 p-6">
        <h2 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
          The four runtime components
        </h2>
        <p className="mt-1 text-xs text-muted-foreground">Tap any component to expand.</p>
        <div className="mt-4 grid gap-2 md:grid-cols-2">
          <Component
            name="Intent classifier"
            desc="Labels each learner turn (direct-answer, conceptual, clarification, meta) to decide which scaffold to fire."
          />
          <Component
            name="Self-Regulated Learning (SRL) scaffolds"
            desc="Three interface prompts (WriteApproachFirst, ParaphraseBeforeProceed, AttemptBeforeReveal) that pause the tutor until the learner plans, paraphrases, or attempts."
          />
          <Component
            name="Counterfactual fairness audit"
            desc="Re-runs each turn under different learner backgrounds (age, life stage, language, education, digital fluency) and flags answers that diverge in depth or jargon."
          />
          <Component
            name="Pseudonymous logging"
            desc="Learner IDs are HMAC-SHA256 hashed before storage. Raw message text is never persisted alongside an identity."
          />
        </div>
      </section>

      <section className="mt-8 rounded-xl border p-6">
        <h2 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
          Learn more
        </h2>
        <div className="mt-4 grid gap-2 md:grid-cols-2">
          <FurtherInfo
            term="Self-Regulated Learning (SRL)"
            desc="A model of learning, due to Zimmerman (2002), in which learners cycle through three phases: forethought (planning), performance (monitoring), and reflection (self-evaluation). SAGE maps one interface scaffold to each phase so the tutor reinforces the cycle instead of bypassing it."
          />
          <FurtherInfo
            term="Counterfactual fairness audit"
            desc="For every turn, the system re-runs the same prompt with the learner described as having a different age, life stage, language background, education, or digital fluency. If the answers diverge in explanation depth or jargon, the turn is flagged and (optionally) regenerated by a rectifier."
          />
          <FurtherInfo
            term="Desirable difficulty"
            desc="Bjork & Bjork (2011) showed that effortful retrieval, being asked to attempt before being told, produces more durable learning than passively reading the answer. The AttemptBeforeReveal scaffold operationalises this finding."
          />
          <FurtherInfo
            term="Why adult business learners?"
            desc="Singapore's SkillsFuture and Continuing Education and Training (CET) context concentrates learners with very mixed prior education, language, and digital fluency in the same classroom. A one-size-fits-all LLM tutor risks giving systematically shallower help to some of them; this tool makes that gap visible and tries to close it."
          />
        </div>
        <p className="mt-5 text-xs text-muted-foreground">
          See the source on GitHub for the full technical write-up.
        </p>
      </section>
    </main>
  );
}

function Card({
  href,
  title,
  subtitle,
  accent,
  badge,
}: {
  href: string;
  title: string;
  subtitle: string;
  accent?: "primary";
  badge?: string;
}) {
  return (
    <Link
      href={href}
      className={
        accent === "primary"
          ? "group rounded-xl border-2 border-primary bg-primary/5 p-6 transition-all hover:bg-primary/10 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
          : "group rounded-xl border p-6 transition-all hover:border-foreground/20 hover:bg-muted/40 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
      }
    >
      <div className="flex items-baseline justify-between gap-3">
        <h2 className="text-lg font-medium">{title}</h2>
        {badge ? (
          <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-primary">
            {badge}
          </span>
        ) : (
          <span className="text-sm text-muted-foreground transition-transform group-hover:translate-x-0.5">
            →
          </span>
        )}
      </div>
      <p className="mt-1.5 text-sm text-muted-foreground">{subtitle}</p>
    </Link>
  );
}

function Component({ name, desc }: { name: string; desc: string }) {
  return (
    <Disclosure title={name} className="bg-background" bodyClassName="text-xs">
      {desc}
    </Disclosure>
  );
}

function FurtherInfo({ term, desc }: { term: string; desc: string }) {
  return (
    <Disclosure title={term} className="bg-background" bodyClassName="text-xs">
      {desc}
    </Disclosure>
  );
}
